name: Build Windows

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Windows
        run: npm run build

      - name: Upload 7z only
        uses: actions/upload-artifact@v4
        with:
          name: windows-7z
          path: dist/poi-*-win.7z
